# Generated by Django 6.1.1 on 2026-09-21 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_name', models.CharField(max_length=100)),
                ('player2_name', models.CharField(max_length=100)),
                ('player1_score', models.PositiveSmallIntegerField(default=0)),
                ('player2_score', models.PositiveSmallIntegerField(default=0)),
                ('ties', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('winner', models.CharField(blank=True, choices=[('PLAYER1', 'Player 1'), ('PLAYER2', 'Player 2'), ('TIE', 'Tie')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('player1_choice', models.CharField(choices=[('STONE', 'Stone'), ('PAPER', 'Paper'), ('SCISSORS', 'Scissors')], max_length=10)),
                ('player2_choice', models.CharField(choices=[('STONE', 'Stone'), ('PAPER', 'Paper'), ('SCISSORS', 'Scissors')], max_length=10)),
                ('winner', models.CharField(choices=[('PLAYER1', 'Player 1'), ('PLAYER2', 'Player 2'), ('TIE', 'Tie')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.game')),
            ],
            options={
                'ordering': ['round_number'],
                'constraints': [models.UniqueConstraint(fields=('game', 'round_number'), name='unique_round_number_per_game'), models.CheckConstraint(condition=models.Q(('round_number__gt', 0)), name='round_number_positive')],
            },
        ),
    ]
